name: My First Workflow

on: push

jobs:
    first_jon:
        runs-on: ubuntu-latest
        steps:
        - name: Wellcomemesaage
          run: echo "My first Github Action Job"

        - name: List files 
          run: ls

        - name: Readfile
          run: cat README.md


