name: Generate Asccik Artwork 
on: 
  push 

Jobs: 
  Ascci_job:
    runs-on: ubuntu-latest
steps:
  - name: check out Repo 
  - uses: actions/checkout@v6
  - name: List Repo Files 
     run: Ls -ltra

  - name: Executin shell script 
     run: ./ascci-script.sh
  
